version: "3"
services:
  main_service:
    build:
      context: .
      dockerfile: ./docker/main_service/Dockerfile
    ports: ["8080:8080"]
    volumes: [./main_service:/main_service]
    environment:
      FLASK_ENV: development
      JWT_SECRET: $JWT_SECRET
  file_service:
    build:
      context: .
      dockerfile: ./docker/file_service/Dockerfile
    ports: ["8081:8081"]
    volumes: [./file_service:/file_service]
    environment:
      FLASK_ENV: development
      JWT_SECRET: $JWT_SECRET
  redis_db:
    image: "redis:alpine"
