version: "3"
services:
  redis_db:
    image: "redis:alpine"
  service_base:
    build:
      context: .
      dockerfile: ./docker/service_base/Dockerfile
    image: service_base:latest
  main_service:
    depends_on:
      - redis_db
      - service_base
    build:
      context: .
      dockerfile: ./docker/main_service/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./main_service:/main_service
      - ./db:/main_service/db
    env_file:
      - variables.env
  courier_service:
    depends_on:
      - redis_db
      - service_base
    build:
      context: .
      dockerfile: ./docker/courier_service/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./courier_service:/courier_service
      - ./db:/courier_service/db
    env_file:
      - variables.env
  mailbox_service:
    depends_on:
      - redis_db
      - service_base
    build:
      context: .
      dockerfile: ./docker/mailbox_service/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./mailbox_service:/mailbox_service
      - ./db:/mailbox_service/db
    env_file:
      - variables.env
  authorization_service:
    depends_on:
      - redis_db
      - service_base
    build:
      context: .
      dockerfile: ./docker/authorization_service/Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./authorization_service:/authorization_service
      - ./db:/authorization_service/db
    env_file:
      - variables.env
  package_service:
    depends_on:
      - redis_db
      - service_base
    build:
      context: .
      dockerfile: ./docker/package_service/Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./package_service:/package_service
      - ./db:/package_service/db
    env_file:
      - variables.env
